module FooModule
  def foo: -> String
end

module BarModule
  def bar: -> String
end

interface _Foo
  def foo: () -> String
end

interface _Bar
  def bar: () -> String
end

class Foo
  include _Foo
end

class BarInheritsFromFoo < Foo
  include _Bar
end

class FooBar
  include _Foo
  include _Bar
end

class Object
  def put_foo_bar: (_Foo & _Bar) -> void
end
